### PR TITLE
Added a toggle button to show/hide sidebar

### PR DESCRIPTION
**Pull request by akhtara838**
I added in a button and a toggleButton function so that when the user clicks on the button, the sidebar is hidden and if they click the button when the sidebar is already hidden, it will become visible.

### CODE REVIEW

**Review by payneBrandon — CHANGES_REQUESTED** [review]
This is looking good! Show/hide functionality works. Let's try to get the Menu to be over the map though, so when we hide it the map is visible underneath. That way the map is using the maximum real estate on the page.

**Comment by akhtara838** [comment]
I just pushed my changes onto my branch. I changed the map width size from "calc(100% - 350px)'' to "100%", so we're using the entire space and placed the toggle button on the header so that it's always visible to the user.

**Review by payneBrandon — DISMISSED** [review]
@akhtara838 I tweaked the show/hide logic to be more react-based rather than manipulating classes from the DOM. Take a look and let me know if you have any questions with it.

**Review by drewjj — APPROVED** [review]
Looks good, just resolve the one conflict remaining

**Comment by akhtara838** [comment]
I fixed all the conflicts. Once it's reviewed, I can merge it in

**Review by payneBrandon — APPROVED** [review]
Looks good to me!

**Pull request merged**
